### ISSUE TITLE
Wrong name and link to repo for urxvt plugin

### ISSUE THREAD

**Issue by trygveaa** [amerlyq/vim-focus-autocmd#1]
> Used in connection with vim-focus-autocmd. Install it for plugin to work in urxvt.

The name and link here is to this repo. It should probably be urxvt-ext-evolved.

Also, it could be clearer that you need that for urxvt. By reading the line above:

> If after update something don't work, you must restart urxvt. Because it sources plugins only at loading time.

It doesn't seem like it is necessary to do anything other than restart urxvt.

**Comment by amerlyq** [comment]
I'm honestly surprised that someone uses this plugin after all:)
It's development was postponed until I re-configure vimrc for nvim, because of some incongruities and necessary to rewise workflow and configurability.
But alright, I will fix it . Thanks.

**Comment by trygveaa** [comment]
Ah, I just found it and started using it after searching for how to get focus events in vim working with urxvt. Thanks for the plugin!
