### ISSUE TITLE
Clarification needed for Konsole

### ISSUE THREAD

**Issue by emugel** [amerlyq/vim-focus-autocmd#3]
Hi, I can't make the focus lost/regained work with Konsole 16.12.0 (Archlinux).
I added those two lines in my .vimrc after adding your plugin: 

```
au FocusGained * echo "Focus GAINED"
au FocusLost * echo "Focus LOST"
```
While it shows with gvim, it won't with vim 8.0 (the latest git release).
Also, I now get some "q" characters sometimes as I type (they are not real characters in the buffer but are visible).

Is there something I misunderstood?
Thanks in advance.

**Comment by amerlyq** [comment]
Be aware that `echo` don't work on Focus* events. 
No idea why, but I remember getting shallow explanation somewhere.
Try with `set number` and `set nonumber` -- as allowed in sandbox commands.
For me Focus* events work on arch with `vim8` and `st`.

**Comment by emugel** [comment]
Oh oh!!! Christmas gift! 
You're right it works with set number / set nonumber!

However everytime I press the escape key a 'q' is inserted.
I will inquiry a bit to see if it's a problem with another plugin, will let you know.

**Comment by emugel** [comment]
Disabling all plugins and trimming the .vimrc there still is the 'q' problem.

It is fixed though if I comment all lines in `autoload/focau/cursor.vim` (I think it's got to do with the escape codes, they all finish with a q).
Could you point me to a clean way to configure the plugin without using the cursor feature? So next time I pull it with git it doesn't break stuffs.

**Comment by amerlyq** [comment]
If you need only events, try disabling g:focau.auto = 0. However whole situation seems rather suspicious. What is your $TERM in Konsole?

**Comment by emugel** [comment]
xterm-256color

Note that if it works flawlessly in urxvt along with your urvxt perl plugin (cursor changes shapes on insert mode, while it doesn't in Konsole and I've got a ghost 'q' instead).
I also tried to disable all plugins, downloaded the plugin again, with the same result for Konsole.

**Comment by amerlyq** [comment]
Did you ever considered that xterm isn't right value for your setup? After
all, $TERM var is usually the sole option to distinguish different
terminals. You have got what you requested - codes for xterm. Use
Konsole-256color instead, to get codes for Konsole. However if it breaks
some other things - google for right value. After all I haven't run Konsole
in long time and its terminfo could somewhat change by now.

**Comment by emugel** [comment]
Set it to konsole-256color
Everything seems to work :)
Thanks a lot man!

**Comment by emugel** [comment]
`TERM=konsole-256color vim` sees your plugin telling me "Can't auto-derive termfocus codes for your $TERM. Disabled. If you disagree, set escape codes by yourself:)"

I'll look into it further.

**Comment by emugel** [comment]
Works perfectly if I add a line like this along with `TERM=konsole-256color`:

```
function! focau#events#auto_choose()
  if $TERM =~ '^rxvt'
    return ["\e]777;focus;on\x7", "\e]777;focus;off\x7"]
  elseif $TERM =~ '\v^%(xterm|st|screen|tmux)' || exists('$ITERM_PROFILE')
    return ["\e[?1004h", "\e[?1004l"]
" I ADDED THIS:
  elseif $TERM =~ '^konsole'
    return ["\e[?1004h", "\e[?1004l"]
  endif
```
Will test it for a couple of days.

**Comment by amerlyq** [comment]
It depends on term. When I developed plugin it was Konsole - with capital
letter. You used konsole with regular letter. If you find official proof
which way is the right one - I will fix it in plugin). May start looking at
/usr/share/terminfo/k/ or around that, arch wiki, etc.

**Comment by amerlyq** [comment]
Alright, I replaced prescribed set to silent defaults and aggregated your fix.
Try it out. If you find out how to change cursor color in Konsole, I may integrate it as well.
